server:
 port: 9092

logging:
 level:
  root: INFO

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javafsd
    username: root
    password: Dheeraj@1234
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
     ddl-auto: update