

logging:
 level:
  root: INFO
spring :
  profiles:
    active: dev
 
---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/javafsd
    username: root
    password: Passw0rd
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
     ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: qa
  datasource:
    url: jdbc:mysql://localhost:3306/javafsd
    username: root
    password: Passw0rd
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
     ddl-auto: update

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/javafsd
    username: root
    password: Passw0rd
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
     ddl-auto: update