server:
 port: 9093

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javafsd
    username: root
    password: Passw0rd
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
  