server:
 port: 9093
 
logging:
 level:
  root: INFO

spring :
  profiles:
    active: qa
  application:
    name: DEPARTMENT-SERVICE
 
---
 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javafsd
    username: root
    password: Gopigopi@9
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
     ddl-auto: update 
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/javafsd
    username: root
    password: Gopigopi@9
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
     ddl-auto: update 
 
---
 
spring:
  profiles: qa
  datasource:
    url: jdbc:mysql://localhost:3306/javafsd-qa
    username: root
    password: Gopigopi@9
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
     ddl-auto: update 

 
---
 
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/javafsd-prod
    username: root
    password: Gopigopi@9
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
     ddl-auto: update

eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
  service-url:
   defaultZone: http://localhost:8761/eureka/
 instance:
  hostnae: localhost