spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javafsd
    username: root
    password: Value@896@
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
     ddl-auto: update