server:
 port: 9092

spring:
  datasource:
    url: jdbc:h2:mem:javafsd
    username: sa
    password: passw0rd
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect