spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javafsd-qa
    username: root
    password: Rohi@1999
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
     ddl-auto: update
  mvc:
   pathmatch:
    matching-strategy: ant_path_matcher