spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javafsd
    username: root
    password: password
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
     ddl-auto: update
spring:
  mvc:
    pathmatch:
     matching-strategy: ant_path_matcher