server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javafsd
    username: root
    password: Passw0rd
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
     ddl-auto: update