server:
 port: 9095
 
 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javafsd
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
     ddl-auto: update 